import type { Metadata } from "next";
import Link from "next/link";
import { Bangers, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bangers = Bangers({
  variable: "--font-bangers",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex items-end justify-between p-4">
          <h1
            className={`${bangers.className} text-4xl tracking-wide text-black dark:text-zinc-50`}
          >
            PokeMatch
          </h1>
          <div className="flex gap-4">
            <Link
              href="/"
              className="text-sm font-medium text-black underline dark:text-zinc-50"
            >
              Home
            </Link>
            <Link
              href="/browse"
              className="text-sm font-medium text-black underline dark:text-zinc-50"
            >
              Browse
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
